######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 1 21:01:23 2010
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS += chi/src src
