######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 18 08:09:26 2010
######################################################################

TEMPLATE = lib

CONFIG += staticlib

INCLUDEPATH += .

OBJECTS_DIR = ../obj
MOC_DIR = ../obj
